In [9]:
import torch
from torch import nn
from d2l import torch as d2l

In [10]:
x = torch.tensor(
    [1, 2, 3]
)

print(x)
print(x.device)

tensor([1, 2, 3])
cpu


In [11]:
# GPU에 Tensor 직접 생성

assert torch.cuda.is_available()

gpu_device = torch.device(
    "cuda:0"
)

# GPU로 지정
X = torch.ones(
    (2, 3),
    device=gpu_device,
)

# CPU로 지정
Y = torch.rand(
    (2, 3),
)

print(X)
print(Y)
print(X.device)
print(Y.device)

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[0.7268, 0.3552, 0.6708],
        [0.5184, 0.5405, 0.9621]])
cuda:0
cpu


In [12]:
# 서로 다른 Device의 연산 실패 확인:
# all tensors have to be on the same device!!!

try:
    X + Y

except RuntimeError as error:
    print(type(error).__name__)
    print(error)

RuntimeError
Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!


In [ ]:
# 같은 Device로 이동한 뒤 연산

Z = Y.to(
    X.device
)

result = X + Z

print(Z)
print(Z.device)
print(result)

tensor([[0.7268, 0.3552, 0.6708],
        [0.5184, 0.5405, 0.9621]], device='cuda:0')
cuda:0
tensor([[1.7268, 1.3552, 1.6708],
        [1.5184, 1.5405, 1.9621]], device='cuda:0')


In [ ]:
Z_again = Z.to(
    X.device
)

print(
    Z_again is Z
)

X_numpy = (
    X
    .cpu()
    .numpy()
)

print(X_numpy)

True
tensor([[1., 1., 1.],
        [1., 1., 1.]])
[[1. 1. 1.]
 [1. 1. 1.]]
