In [ ]:
from pathlib import Path

import torch
from torch import nn
from torch.nn import functional as F
from d2l import torch as d2l

In [8]:
# 단일 Tensor 저장

data_dir = Path("data")
data_dir.mkdir(
    exist_ok=True
)

x = torch.arange(4)

x_path = (
    data_dir
    / "x-file.pt"
)

torch.save(
    x,
    x_path,
)

print(x)
print(x_path)

tensor([0, 1, 2, 3])
data/x-file.pt


In [9]:
# 단일 Tensor 불러오기

x2 = torch.load(
    x_path,
    weights_only=True,
)

print(x2)
print(
    torch.equal(
        x,
        x2,
    )
)

tensor([0, 1, 2, 3])
True


In [10]:
# 여러 Tensor를 List로 저장하고 불러오기

y = torch.zeros(4)

tensors_path = (
    data_dir
    / "x-files.pt"
)

torch.save(
    [x, y],
    tensors_path,
)

x2, y2 = torch.load(
    tensors_path,
    weights_only=True,
)

print(x2)
print(y2)

tensor([0, 1, 2, 3])
tensor([0., 0., 0., 0.])


In [11]:
# Tensor Dictionary 저장하고 불러오기

tensor_dict = {
    "x": x,
    "y": y,
}

dictionary_path = (
    data_dir
    / "mydict.pt"
)

torch.save(
    tensor_dict,
    dictionary_path,
)

loaded_dict = torch.load(
    dictionary_path,
    weights_only=True,
)

print(loaded_dict)
print(loaded_dict["x"])
print(loaded_dict["y"])

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}
tensor([0, 1, 2, 3])
tensor([0., 0., 0., 0.])
