In [1]:
import torch
from torch import nn

torch.manual_seed(42)

In [7]:
features = torch.tensor([
    [1.0, 2.0, 3.0],
    [2.0, 1.0, 0.0],
    [3.0, 4.0, 1.0],
    [4.0, 3.0, 2.0],
])

weights = torch.tensor([
    [2.0],
    [-1.0],
    [0.5],
])

bias = torch.tensor([3.0])

manual_output = features @ weights + bias

print("Features shape:", features.shape)
print("Weights shape:", weights.shape)
print("Output:")
print(manual_output)
print("Output shape:", manual_output.shape)

Features shape: torch.Size([4, 3])
Weights shape: torch.Size([3, 1])
Output:
tensor([[4.5000],
        [6.0000],
        [5.5000],
        [9.0000]])
Output shape: torch.Size([4, 1])


In [ ]:
# 입력 feature 3개가 출력 뉴런 1개에 모두 연결됨
linear = nn.Linear(
    in_features=3,
    out_features=1,
)

# nn.Linear의 weight shape는 (out_features, in_features) 이므로
# 수동 계산에서 사용한 weights를 transpose해서 복사한다.
with torch.no_grad():
    linear.weight.copy_(weights.T)
    linear.bias.copy_(bias)
    
network_output = linear(features)

print("Layer weight shape:", linear.weight.shape)
print("Layer bias shape:", linear.bias.shape)
print("Network output:")
print(network_output)

Layer weight shape: torch.Size([1, 3])
Layer bias shape: torch.Size([1])
Network output:
tensor([[4.5000],
        [6.0000],
        [5.5000],
        [9.0000]], grad_fn=<AddmmBackward0>)


In [ ]:
# 완전연결층의 전체 parameter 개수:
# weight 3개 + bias 1개 = 4개
number_of_parameters = sum(
    parameter.numel()
    for parameter in linear.parameters()
)

print("Number of parameters:", number_of_parameters)

Number of parameters: 4


In [14]:
# 선형층도 일반적인 신경망 layer 이므로
# loss.backward()를 통해 weight와 bias의 gradient를 계산할 수 있다.
labels = torch.tensor([
    [4.0],
    [7.0],
    [8.0],
    [10.0],
])

predictions = linear(features)
loss = (0.5 * (predictions - labels).pow(2)).mean()

linear.zero_grad()
loss.backward()

print("Loss:", loss.item())

print("\nWeight gradient:")
print(linear.weight.grad)
print("Weight gradient shape:", linear.weight.grad.shape)

print("\nBias gradient:")
print(linear.bias.grad)
print("Bias gradient shape:", linear.bias.grad.shape)

Loss: 1.0625

Weight gradient:
tensor([[-3.2500, -3.2500, -0.7500]])
Weight gradient shape: torch.Size([1, 3])

Bias gradient:
tensor([-1.])
Bias gradient shape: torch.Size([1])
