In [1]:
# PyTorch의 원소별 연산과 텐서 결합 연산을 사용한다.
import torch


In [2]:
# torch.exp는 각 원소에 지수 함수를 적용하므로 입력과 출력 shape가 같다.
# 핵심: exp는 각 원소에 독립적으로 적용되는 원소별 연산이므로 입력과 출력 shape가 같다.
x = torch.arange(12, dtype=torch.float32)
x = x.reshape(3, 4)
exp_x = torch.exp(x)

print("Original x:")
print(x)
print("shape:", x.shape)

print("\nElementwise exponential:")
print(exp_x)
print("shape:", exp_x.shape)

Original x:
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
shape: torch.Size([3, 4])

Elementwise exponential:
tensor([[1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01],
        [5.4598e+01, 1.4841e+02, 4.0343e+02, 1.0966e+03],
        [2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04]])
shape: torch.Size([3, 4])


In [3]:
# 크기가 같은 텐서끼리 산술 연산을 하면 대응하는 원소별로 계산된다.
# 핵심: 같은 shape의 텐서 산술은 대응 원소끼리 계산하며, shape가 다르면 broadcasting 가능성을 검사한다.
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2.0, 2, 2, 2])

addition = x + y
subtraction = x - y
multiplication = x * y
division = x / y
exponentiation = x ** y

print("Original vectors:")
print("x:", x)
print("y:", y)

print("\nElementwise arithmetic:")
print("x + y:", addition)
print("x - y:", subtraction)
print("x * y:", multiplication)
print("x / y:", division)
print("x ** y:", exponentiation)

Original vectors:
x: tensor([1., 2., 4., 8.])
y: tensor([2., 2., 2., 2.])

Elementwise arithmetic:
x + y: tensor([ 3.,  4.,  6., 10.])
x - y: tensor([-1.,  0.,  2.,  6.])
x * y: tensor([ 2.,  4.,  8., 16.])
x / y: tensor([0.5000, 1.0000, 2.0000, 4.0000])
x ** y: tensor([ 1.,  4., 16., 64.])


In [4]:
# torch.cat은 기존 차원을 따라 텐서를 이어 붙이며 dim에 따라 결과 shape가 달라진다.
# 핵심: cat은 새 축을 만들지 않고 지정한 dim의 길이를 더하며 나머지 축의 길이는 같아야 한다.
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([
    [2.0, 1, 4, 3],
    [1, 2, 3, 4],
    [4, 3, 2, 1],
])

rows_concatenated = torch.cat((X, Y), dim=0)
columns_concatenated = torch.cat((X, Y), dim=1)

print("Original tensors:")
print("X:")
print(X)
print("Y:")
print(Y)

print("\nConcatenate along axis 0:")
print(rows_concatenated)
print("Shape:", rows_concatenated.shape)

print("\nConcatenate along axis 1:")
print(columns_concatenated)
print("Shape:", columns_concatenated.shape)

Original tensors:
X:
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
Y:
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

Concatenate along axis 0:
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
Shape: torch.Size([6, 4])

Concatenate along axis 1:
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])
Shape: torch.Size([3, 8])


In [5]:
# 비교 연산은 원소별 True/False를 담은 bool 텐서를 반환한다.
# 핵심: 비교 결과는 bool 텐서이고, bool의 합은 True를 1로 보아 조건을 만족한 원소 수를 센다.
comparison = (X == Y)

print("Elementwise comparison:")
print(comparison)
print("shape:", comparison.shape)
print("dtype:", comparison.dtype)
print("Equal elements:", comparison.sum().item())

Elementwise comparison:
tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])
shape: torch.Size([3, 4])
dtype: torch.bool
Equal elements: 2


In [6]:
# sum은 모든 원소를 하나의 0차원 텐서로 축약하고 item은 Python 숫자를 꺼낸다.
# 핵심: 모든 축을 sum하면 0차원 텐서가 되고 item은 이를 autograd 밖의 Python 숫자로 꺼낸다.
total = X.sum()

print("Sum of all elements:")
print(total)
print("shape:", total.shape)
print("python scalar:", total.item())

Sum of all elements:
tensor(66.)
shape: torch.Size([])
python scalar: 66.0
