In [ ]:
# 서로 다른 shape의 텐서를 자동 확장하는 broadcasting을 확인한다.
import torch    

In [ ]:
# (3, 1)과 (1, 2)는 각 크기가 1인 차원을 확장할 수 있도록 준비된 shape다.
# 핵심: broadcasting은 shape를 오른쪽부터 비교하며 두 길이가 같거나 하나가 1이면 호환된다.
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)

print("Original tensors:")
print("a:")
print(a)
print("Shape:", a.shape)

print("\nb:")
print(b)
print("Shape:", b.shape)

Original tensors:
a:
tensor([[0],
        [1],
        [2]])
Shape: torch.Size([3, 1])

b:
tensor([[0, 1]])
Shape: torch.Size([1, 2])


In [ ]:
# broadcasting은 두 shape를 오른쪽부터 비교해 호환되는 차원을 자동 확장한다.
# 핵심: a + b는 (3, 1)과 (1, 2)를 논리적으로 (3, 2)로 확장해 원소별 덧셈한다.
result = a + b

print("Broadcasting result:")
print(result)
print("shape:", result.shape)

Broadcasting result:
tensor([[0, 1],
        [1, 2],
        [2, 3]])
shape: torch.Size([3, 2])


In [ ]:
# expand는 실제 데이터를 복사하지 않고 확장된 view를 만든다.
# 핵심: expand는 데이터를 복사하지 않는 view를 만들므로 메모리는 절약되지만 제자리 수정은 주의해야 한다.
a_expanded = a.expand(3, 2)
b_expanded = b.expand(3, 2)

print("Expanded a:")
print(a_expanded)
print("Shape:", a_expanded.shape)

print("\nExpanded b:")
print(b_expanded)
print("Shape:", b_expanded.shape)

print("\nExplicitly expanded result:")
print(a_expanded + b_expanded)

Expanded a:
tensor([[0, 0],
        [1, 1],
        [2, 2]])
Shape: torch.Size([3, 2])

Expanded b:
tensor([[0, 1],
        [0, 1],
        [0, 1]])
Shape: torch.Size([3, 2])

Explicitly expanded result:
tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [ ]:
# (B, T, D) 특징에 (D,) bias를 더하면 마지막 차원 D를 기준으로 broadcasting된다.
# 핵심: (B, T, D) + (D,)에서는 마지막 D축이 맞춰져 모든 batch와 token에 같은 bias가 더해진다.
B, T, D = 2, 3, 4

features = torch.arange(B * T * D).reshape(B, T, D)
bias = torch.tensor([10, 20, 30, 40])

output = features + bias

print("Features:")
print(features)
print("Shape:", features.shape)

print("\nBias:")
print(bias)
print("Shape:", bias.shape)

print("\nBroadcasting result:")
print(output)
print("Shape:", output.shape)

Features:
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
Shape: torch.Size([2, 3, 4])

Bias:
tensor([10, 20, 30, 40])
Shape: torch.Size([4])

Broadcasting result:
tensor([[[10, 21, 32, 43],
         [14, 25, 36, 47],
         [18, 29, 40, 51]],

        [[22, 33, 44, 55],
         [26, 37, 48, 59],
         [30, 41, 52, 63]]])
Shape: torch.Size([2, 3, 4])
