In [1]:
# 메모리 할당 방식의 차이를 비교할 동일한 shape의 텐서 두 개를 만든다.
import torch

X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([
    [2.0, 1, 4, 3],
    [1, 2, 3, 4],
    [4, 3, 2, 1],
])

print("Original tensors:")
print("X:")
print(X)
print("Y:")
print(Y)

Original tensors:
X:
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
Y:
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])


In [ ]:
# Y = Y + X는 계산 결과를 위한 새 객체와 새 저장 공간을 만든다.
original_Y = Y
before_id = id(Y)
before_ptr = Y.data_ptr()

Y = Y + X

after_id = id(Y)
after_ptr = Y.data_ptr()

print("Out-of-place operation:")
print(Y)

print("\nObject identity:")
print("Before:", before_id)
print("After:", after_id)
print("Same object:", before_id == after_id)

print("\nStorage address:")
print("Before:", before_ptr)
print("After:", after_ptr)
print("Same storage:", before_ptr == after_ptr)

Out-of-place operation:
tensor([[ 2.,  2.,  6.,  6.],
        [ 5.,  7.,  9., 11.],
        [12., 12., 12., 12.]])

Object identity:
Before: 131396021344592
After: 131390262206032
Same object: False

Storage address:
Before: 306005952
After: 206963328
Same storage: False


In [4]:
# 미리 만든 Z에 슬라이스 대입하면 Z의 객체와 저장 공간을 그대로 재사용한다.
Z = torch.zeros_like(Y)

before_id = id(Z)
before_ptr = Z.data_ptr()

Z[:] = X + Y

after_id = id(Z)
after_ptr = Z.data_ptr()

print("Preallocated tensor:")
print(Z)

print("\nObject identity:")
print("Before:", before_id)
print("After:", after_id)
print("Same object:", before_id == after_id)

print("\nStorage address:")
print("Before:", before_ptr)
print("After:", after_ptr)
print("Same storage:", before_ptr == after_ptr)

Preallocated tensor:
tensor([[ 2.,  3.,  8.,  9.],
        [ 9., 12., 15., 18.],
        [20., 21., 22., 23.]])

Object identity:
Before: 131390262209152
After: 131390262209152
Same object: True

Storage address:
Before: 312570624
After: 312570624
Same storage: True


In [7]:
# += 제자리 연산은 기존 저장 공간을 수정하므로 같은 객체를 가리키는 alias에도 반영된다.
X_inplace = X.clone()
alias = X_inplace

before_id = id(X_inplace)
before_ptr = X_inplace.data_ptr()

X_inplace += Y

after_id = id(X_inplace)
after_ptr = X_inplace.data_ptr()

print("In-place operation:")
print(X_inplace)

print("\nObject identity:")
print("Before:", before_id)
print("After:", after_id)
print("Same object:", before_id == after_id)

print("\nStorage address:")
print("Before:", before_ptr)
print("After:", after_ptr)
print("Same storage:", before_ptr == after_ptr)

print("\nAlias sees updated values:")
print(alias)

In-place operation:
tensor([[ 2.,  3.,  8.,  9.],
        [ 9., 12., 15., 18.],
        [20., 21., 22., 23.]])

Object identity:
Before: 131390262518608
After: 131390262518608
Same object: True

Storage address:
Before: 314359872
After: 314359872
Same storage: True

Alias sees updated values:
tensor([[ 2.,  3.,  8.,  9.],
        [ 9., 12., 15., 18.],
        [20., 21., 22., 23.]])
