In [1]:
# CPU 텐서와 NumPy 배열 사이의 변환 및 메모리 공유를 확인한다.
import torch

X = torch.arange(12, dtype=torch.float32).reshape(3, 4)

# 텐서 -> 배열
A = X.numpy()

# 배열 -> 텐서
B = torch.from_numpy(A)

print("PyTorch tensor X:")
print(X)
print("Type:", type(X))

print("\nNumPy array A:")
print(A)
print("Type:", type(A))

print("\nPyTorch tensor B:")
print(B)
print("Type:", type(B))

PyTorch tensor X:
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
Type: <class 'torch.Tensor'>

NumPy array A:
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
Type: <class 'numpy.ndarray'>

PyTorch tensor B:
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
Type: <class 'torch.Tensor'>


In [2]:
# A와 B는 X와 메모리를 공유하므로 한쪽의 제자리 변경이 다른 쪽에도 반영된다.
A[0, 0] = 100

print("After changing A[0, 0]:")
print("X:")
print(X)

print("\nA:")
print(A)

print("\nB:")
print(B)


# B를 제자리에서 변경해도 X와 A에 반영된다.
B[0, 1] = -1

print("\nAfter changing B[0, 1]:")
print("X:")
print(X)

print("\nA:")
print(A)

After changing A[0, 0]:
X:
tensor([[100.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.],
        [  8.,   9.,  10.,  11.]])

A:
[[100.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]]

B:
tensor([[100.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.],
        [  8.,   9.,  10.,  11.]])

After changing B[0, 1]:
X:
tensor([[100.,  -1.,   2.,   3.],
        [  4.,   5.,   6.,   7.],
        [  8.,   9.,  10.,  11.]])

A:
[[100.  -1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]]


In [3]:
# 원소가 하나인 텐서는 item 또는 Python 내장 함수로 스칼라 값으로 변환할 수 있다.
a = torch.tensor([3.5])

# item()은 원소가 정확히 하나일 때만 사용할 수 있다.
python_value = a.item()
float_value = float(a)
integer_value = int(a)

print("Original tensor:")
print(a)
print("Shape:", a.shape)

print("\nConverted values:")
print("a.item():", python_value, type(python_value))
print("float(a):", float_value, type(float_value))
print("int(a):", integer_value, type(integer_value))

Original tensor:
tensor([3.5000])
Shape: torch.Size([1])

Converted values:
a.item(): 3.5 <class 'float'>
float(a): 3.5 <class 'float'>
int(a): 3 <class 'int'>


In [4]:
# NumPy 변환 전 detach로 계산 그래프를 끊고 cpu로 데이터를 CPU 메모리에 옮긴다.
scores = torch.tensor([1.5, 2.5], requires_grad=True)

# requires_grad=True인 텐서는 바로 NumPy 배열로 변환할 수 없다.
# try:
#     scores.numpy()
# except RuntimeError as error:
#     print("Direct conversion failed:")
#     print(error)
    
# detach()는 계산 그래프에서 분리하고,
# cpu()는 GPU 텐서도 NumPy가 사용할 수 있도록 CPU로 옮긴다.
safe_scores = scores.detach().cpu().numpy()

print("\nSafely converted NumPy array:")
print(safe_scores)
print("Type:", type(safe_scores))


Safely converted NumPy array:
[1.5 2.5]
Type: <class 'numpy.ndarray'>
