# D2L 2.1 Data Manipulation 빈칸 채우기

각 문제의 `...`를 알맞은 코드로 바꾼 뒤 해당 셀을 실행하세요.

In [2]:
import torch

In [3]:
# 문제 1. 텐서 생성
# 0부터 11까지의 값을 가진 float32 텐서를 만든다.
# 핵심: arange(stop)는 0부터 stop - 1까지 만들며 dtype을 직접 지정할 수 있다.
x = torch.arange(12, dtype = torch.float32)

print(x)
print("Shape:", x.shape)
print("Dtype:", x.dtype)

assert x.shape == (12,)
assert x.dtype == torch.float32

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])
Shape: torch.Size([12])
Dtype: torch.float32


In [4]:
# 문제 2. reshape
# x를 3행 4열의 텐서로 바꾼다.
# 핵심: reshape는 원소 수를 유지하고 shape만 바꾼다.
x = torch.arange(12, dtype=torch.float32)
X = torch.reshape(x, (3, 4))

print(X)
print("Shape:", X.shape)

assert X.shape == (3, 4)
assert X.numel() == x.numel()

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
Shape: torch.Size([3, 4])


In [5]:
# 문제 3. 인덱싱과 슬라이싱
# 마지막 행과 왼쪽 위 2 x 2 부분 행렬을 선택한다.
# 핵심: 정수 인덱싱은 차원을 줄일 수 있지만 슬라이싱은 해당 차원을 유지한다.
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)

last_row = X[-1]
top_left = X[:2, :2]

print("Last row:")
print(last_row)
print("Shape:", last_row.shape)

print("\nTop-left submatrix:")
print(top_left)
print("Shape:", top_left.shape)

assert last_row.shape == (4,)
assert top_left.shape == (2, 2)

Last row:
tensor([ 8.,  9., 10., 11.])
Shape: torch.Size([4])

Top-left submatrix:
tensor([[0., 1.],
        [4., 5.]])
Shape: torch.Size([2, 2])


In [6]:
# 문제 4. 원소별 연산
# x와 y의 덧셈, 곱셈, 크기 비교를 완성한다.
# 핵심: 산술과 비교는 원소별로 수행되며 비교 결과의 dtype은 bool이다.
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2.0, 2, 2, 2])

addition = x + y
multiplication = x * y
greater_than = x > y

print("x + y:", addition)
print("x * y:", multiplication)
print("x > y:", greater_than)

assert addition.tolist() == [3.0, 4.0, 6.0, 10.0]
assert multiplication.tolist() == [2.0, 4.0, 8.0, 16.0]
assert greater_than.dtype == torch.bool

x + y: tensor([ 3.,  4.,  6., 10.])
x * y: tensor([ 2.,  4.,  8., 16.])
x > y: tensor([False, False,  True,  True])


In [7]:
# 문제 5. 텐서 연결
# X와 Y를 행 방향과 열 방향으로 각각 연결한다.
# 핵심: dim=0은 행 방향, dim=1은 열 방향으로 연결하며 나머지 차원 크기는 같아야 한다.
X = torch.arange(6).reshape(2, 3)
Y = torch.arange(6, 12).reshape(2, 3)

rows_concatenated = torch.cat((X, Y), dim=0)
columns_concatenated = torch.cat((X, Y), dim=1)

print("Row concatenation:")
print(rows_concatenated)
print("Shape:", rows_concatenated.shape)

print("\nColumn concatenation:")
print(columns_concatenated)
print("Shape:", columns_concatenated.shape)

assert rows_concatenated.shape == (4, 3)
assert columns_concatenated.shape == (2, 6)

Row concatenation:
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
Shape: torch.Size([4, 3])

Column concatenation:
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])
Shape: torch.Size([2, 6])


In [8]:
# 문제 6. broadcasting
# (3, 1) 텐서와 (1, 2) 텐서를 더한다.
# 핵심: expand 없이 a + b만 써도 자동 broadcasting되며 expand는 데이터를 복사하지 않는 view다.
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)

result = a.expand(3, 2) + b.expand(3, 2)

print(result)
print("Shape:", result.shape)

assert result.shape == (3, 2)
assert result.tolist() == [[0, 1], [1, 2], [2, 3]]

tensor([[0, 1],
        [1, 2],
        [2, 3]])
Shape: torch.Size([3, 2])


In [9]:
# 문제 7. 기존 메모리 재사용
# X + Y의 결과를 Z의 기존 저장 공간에 대입한다.
# 핵심: Z[:] 대입은 Z의 객체와 저장 공간을 유지한다. 단, X + Y 결과용 임시 텐서는 생성된다.
X = torch.arange(6, dtype=torch.float32).reshape(2, 3)
Y = torch.ones((2, 3))
Z = torch.zeros_like(X)

before_ptr = Z.data_ptr()

Z[:] = X + Y

after_ptr = Z.data_ptr()

print(Z)
print("Same storage:", before_ptr == after_ptr)

assert before_ptr == after_ptr
assert torch.equal(Z, X + Y)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
Same storage: True


In [ ]:
# 문제 8. NumPy 배열과 메모리 공유
# X를 NumPy 배열로 바꾸고, 그 배열로 다시 PyTorch 텐서를 만든다.
# 핵심: numpy()와 from_numpy()는 CPU 메모리를 공유하지만 torch.tensor(A)는 데이터를 복사한다.
X = torch.arange(6, dtype=torch.float32)

A = X.numpy() # 텐서 -> 배열
B = torch.from_numpy(A) # 배열 -> 텐서

A[0] = 100

print("X:", X)
print("A:", A)
print("B:", B)

assert X[0].item() == 100
assert B[0].item() == 100

X: tensor([100.,   1.,   2.,   3.,   4.,   5.])
A: [100.   1.   2.   3.   4.   5.]
B: tensor([100.,   1.,   2.,   3.,   4.,   5.])


In [11]:
# 문제 9. Python 스칼라 변환
# 원소가 하나인 텐서에서 Python float 값을 꺼낸다.
# 핵심: item()은 원소가 하나인 텐서만 Python 스칼라로 변환하며 autograd 연결은 이어지지 않는다.
a = torch.tensor([3.5])

value = a.item()

print(value)
print("Type:", type(value))

assert value == 3.5
assert isinstance(value, float)

3.5
Type: <class 'float'>
