In [2]:
import torch

In [ ]:
# arange(3)은 0부터 2까지의 값을 가진 1차원 텐서를 만든다.
# 핵심: 벡터는 축 하나를 가진 1차 텐서이고 shape의 유일한 값이 벡터의 차원성이다.
x = torch.arange(3)

print("Vector x:")
print(x) # tensor([0, 1, 2])

print("\nProperties:")
print("shape:", x.shape) # [3]
print("number of axes:", x.ndim) # 1
print("length:", len(x)) # 3
print("number of elements:", x.numel()) # 3

Vector x:
tensor([0, 1, 2])

Properties:
shape: torch.Size([3])
number of axes: 1
length: 3
number of elements: 3


In [ ]:
# Python의 인덱스는 0부터 시작한다.

# 핵심: 수학의 x₁은 Python의 x[0]에 대응하며 정수 인덱싱 결과는 0차원 스칼라다.
first_element = x[0]
second_element = x[1]
third_element = x[2]

print("x[0]:", first_element) # tensor(0) != tensor([0])
print("x[1]:", second_element)
print("x[2]:", third_element)

# 단일 원소를 선택하면 결과는 0차원 스칼라 텐서다.
print("\nShape of x[2]:", third_element.shape)

x[0]: tensor(0)
x[1]: tensor(1)
x[2]: tensor(2)

Shape of x[2]: torch.Size([])


In [ ]:
# 1차원 텐서를 행벡터와 열벡터 형태로 명시적으로 변경한다
# 핵심: shape (D,)에는 행·열 방향이 없고 (1, D)는 행벡터, (D, 1)은 열벡터다.
row_vector = x.reshape(1, -1)
column_vector = x.reshape(-1, 1)

print("Original vector:")
print(x)
print("Shape:", x.shape) # torch.Size([3])

print("\nRow vector:")
print(row_vector)
print("Shape:", row_vector.shape) # torch.Size([1, 3])

print("\nColumn vector:")
print(column_vector)
print("Shape:", column_vector.shape) # torch.Size([3, 1])

Original vector:
tensor([0, 1, 2])
Shape: torch.Size([3])

Row vector:
tensor([[0, 1, 2]])
Shape: torch.Size([1, 3])

Column vector:
tensor([[0],
        [1],
        [2]])
Shape: torch.Size([3, 1])


In [ ]:
# 벡터의 각 원소가 하나의 스칼라 loss에 어떻게 기여하는지 확인
# 핵심: loss = Σxᵢ²이면 각 성분으로 흐르는 gradient는 ∂loss/∂xᵢ = 2xᵢ다.
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)

loss = (x ** 2).sum()
loss.backward()

print("loss:", loss)

# loss = x₁² + x₂² + x₃²이므로 각 gradient는 2xᵢ다.
print("gradient:", x.grad)

print("loss.shape:", loss.shape) # 스칼라

loss: tensor(14., grad_fn=<SumBackward0>)
gradient: tensor([2., 4., 6.])
loss.shape: torch.Size([])
