In [1]:
import torch

In [2]:
# 6개의 원소를 3행 2열의 행렬을 배치한다.
# 핵심: 행렬은 shape (m, n)인 2차 텐서이며 m은 행 수, n은 열 수다.
A = torch.arange(6).reshape(3, 2)

print("Matrix A:")
print(A)

print("\nProperties:")
print("Shape:", A.shape) # [3, 2]
print("Number of axes:", A.ndim) # 2
print("Number of elements:", A.numel()) # 6

Matrix A:
tensor([[0, 1],
        [2, 3],
        [4, 5]])

Properties:
Shape: torch.Size([3, 2])
Number of axes: 2
Number of elements: 6


In [3]:
# 정수 인덱싱으로 행렬의 개별 스칼라 원소에 접근한다.
# 핵심: 수학의 aᵢⱼ는 Python에서 A[i-1, j-1]에 대응하고 두 정수 인덱스는 스칼라를 반환한다.
first_element = A[0, 0]
second_row_first_column = A[1, 0]
last_element = A[-1, -1]

print("A[0, 0]:", first_element)
print("A[1, 0]:", second_row_first_column)
print("A[-1, -1]:", last_element)

A[0, 0]: tensor(0)
A[1, 0]: tensor(2)
A[-1, -1]: tensor(5)


In [4]:
# 전치는 행과 열을 교환하므로 shape도 반대로 바뀐다.
# 핵심: 전치 A.T는 행과 열을 교환해 shape를 (m, n)에서 (n, m)으로 바꾼다.
A_transposed = A.T

print("Original A:")
print(A)
print("Shape:", A.shape)

print("\nTransposed A:")
print(A_transposed)
print("Shape:", A_transposed.shape)

Original A:
tensor([[0, 1],
        [2, 3],
        [4, 5]])
Shape: torch.Size([3, 2])

Transposed A:
tensor([[0, 2, 4],
        [1, 3, 5]])
Shape: torch.Size([2, 3])


In [ ]:
# 대칭행렬은 정사각행렬이며 자신의 전치와 완전히 같다.
# 핵심: 대칭행렬은 정사각행렬이며 모든 i, j에 대해 aᵢⱼ = aⱼᵢ, 즉 A = A.T를 만족한다.
symmetric_matrix = torch.tensor([
    [1, 2, 3],
    [2, 0, 4],
    [3, 4, 5],
])

is_symmetric = torch.equal(
    symmetric_matrix,
    symmetric_matrix.T
)

print("Symmetric matrix:")
print(symmetric_matrix)

print("\nIs symmetric:", is_symmetric)

NameError: name 'torch' is not defined

: 

In [ ]:
# 데이터 행렬에서는 각 행이 하나의 사례, 각 열이 하나의 특징을 나타낸다.
# 핵심: 표 형식 데이터 행렬에서는 행이 사례, 열이 특징이며 shape는 (num_examples, num_features)다.
dataset = torch.tensor([
    [25.0, 5000.0, 2.0],
    [31.0, 6200.0, 5.0],
    [42.0, 7100.0, 8.0],
    [26.0, 4300.0, 4.0],
])

num_examples, num_features = dataset.shape

print("Dataset:")
print(dataset)

print("\nNumber of examples:", num_examples)
print("Number of features:", num_features)

Dataset:
tensor([[2.5000e+01, 5.0000e+03, 2.0000e+00],
        [3.1000e+01, 6.2000e+03, 5.0000e+00],
        [4.2000e+01, 7.1000e+03, 8.0000e+00],
        [2.6000e+01, 4.3000e+03, 4.0000e+00]])

Number of examples: 4
Number of features: 3


: 