In [1]:
import torch

In [3]:
# 24개의 값을 shape가 (2, 3, 4)인 3차 텐서로 배치한다.
# 핵심: 고차 텐서의 차수는 축 개수이고 전체 원소 수는 shape의 모든 축 길이를 곱한 값이다.
X = torch.arange(24).reshape(2, 3, 4)

print("Tensor X:")
print(X)

print("\nProperties:")
print("shape:", X.shape) # [2, 3, 4]
print("number of axes:", X.ndim) # 3
print("number of elements:", X.numel()) # 24

assert X.shape == (2, 3, 4)
assert X.ndim == 3
assert X.numel() == 24

Tensor X:
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

Properties:
shape: torch.Size([2, 3, 4])
number of axes: 3
number of elements: 24


In [6]:
# 세 개의 인덱스를 지정하면 하나의 스칼라 원소가 선택된다.
# 핵심: 정수 인덱싱은 선택한 축을 제거하지만 범위 슬라이싱은 길이가 1이어도 그 축을 유지한다.
single_value = X[1, 2, 3]

# 첫 번째 축만 인덱싱하면 나머지 두 축은 유지된다.
second_matrix = X[1]

# 슬라이싱은 선택한 축을 유지한다.
first_matrix_slice = X[0:1]

print("X[1, 2, 3]:", single_value)
print("Shape:", single_value.shape)

print("\nX[1]:")
print(second_matrix)
print("Shape:", second_matrix.shape)

print("\nX[0:1] shape:", first_matrix_slice.shape)
print("X[0:1]:\n", first_matrix_slice)

X[1, 2, 3]: tensor(23)
Shape: torch.Size([])

X[1]:
tensor([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])
Shape: torch.Size([3, 4])

X[0:1] shape: torch.Size([1, 3, 4])
X[0:1]:
 tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]])


In [8]:
# D2L의 이미지 표기는 일반적으로 (H, W, C)를 사용한다.
# 핵심: permute는 데이터를 재배열해 복사하지 않고 축 순서만 바꾼 view를 만든다.
height, width, channels = 4, 5, 3
image_hwc = torch.zeros((height, width, channels))

# PyTorch의 CNN은 일반적으로 channel을 앞에 둔 (C, H, W)를 사용한다.
image_chw = image_hwc.permute(2, 0, 1) # (channels, height, width)

print("HWC image shape:", image_hwc.shape)
print("CHW image shape:", image_chw.shape)

HWC image shape: torch.Size([4, 5, 3])
CHW image shape: torch.Size([3, 4, 5])


In [9]:
# 여러 이미지를 batch로 묶으면 PyTorch에서는 일반적으로 (N, C, H, W)를 사용
# 핵심: PyTorch 이미지 batch의 표준 shape는 (N, C, H, W)이며 첫 축 N이 서로 다른 이미지를 구분한다.
batch_size = 2

image_batch = torch.zeros((
    batch_size, # 2
    channels,   # 3
    height,     # 4
    width,      # 5
))

first_image = image_batch[0]

print("Image batch shape:", image_batch.shape)
print("First image shape:", first_image.shape)

Image batch shape: torch.Size([2, 3, 4, 5])
First image shape: torch.Size([3, 4, 5])


In [ ]:
# Transformer의 입력은 일반적으로 (B, T, D) 형태의 3차 텐서다.
# 핵심: Transformer hidden state의 shape (B, T, D)는 batch, token 위치, embedding 성분을 뜻한다.
batch_size = 2
sequence_length = 3
model_dimension = 4

hidden_states = torch.arange(
    batch_size * sequence_length * model_dimension, # [2, 3, 4]
    dtype=torch.float32,
).reshape(batch_size, sequence_length, model_dimension)

# 첫 번째 batch의 두 번째 token 벡터를 선택한다.
token_vector = hidden_states[0, 1] # [4]

print("Hidden states shape:", hidden_states.shape)
print("Token vector:", token_vector)
print("Token vector shape:", token_vector.shape)

assert hidden_states.shape == (2, 3, 4)
assert token_vector.shape == (4,)

Hidden states shape: torch.Size([2, 3, 4])
Token vector: tensor([4., 5., 6., 7.])
Token vector shape: torch.Size([4])


: 