In [1]:
import torch

In [3]:
# clone은 값이 같은 독립적인 텐서를 새 메모리에 만든다.
# 핵심: 원소별 덧셈은 shape를 보존하고 clone은 값은 같지만 저장 공간이 독립적인 텐서를 만든다.
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()

addition = A + B

print("A:")
print(A)

print("\nB:")
print(B)

print("\nA + B:")
print(addition)
print("Shape:", addition.shape)

assert torch.equal(A, B)
assert A.data_ptr() != B.data_ptr()
assert addition.shape == A.shape

A:
tensor([[0., 1., 2.],
        [3., 4., 5.]])

B:
tensor([[0., 1., 2.],
        [3., 4., 5.]])

A + B:
tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])
Shape: torch.Size([2, 3])


In [4]:
# Hadamard product는 같은 위치의 원소끼리 곱한다.
# 핵심: Hadamard product A * B는 같은 위치의 원소끼리 곱하며 일반 행렬 곱과 다르다.
hadamard_product = A * B

print("A * B:")
print(hadamard_product)
print("shape:", hadamard_product.shape)

expected = torch.tensor([
    [0.0, 1.0, 4.0],
    [9.0, 16.0, 25.0],
])

assert torch.equal(hadamard_product, expected)
assert hadamard_product.shape == A.shape

A * B:
tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])
shape: torch.Size([2, 3])


In [5]:
# 스칼라는 모든 원소에 자동으로 broadcasting된다.
# 핵심: 스칼라는 텐서의 모든 위치로 broadcasting되므로 연산 전후 tensor shape가 유지된다.
scalar = 2
X = torch.arange(24).reshape(2, 3, 4)

scalar_added = scalar + X
scalar_multiplied = scalar * X

print("Original X:")
print(X)
print("Shape:", X.shape)

print("\n2 + X:")
print(scalar_added)

print("\n2 * X:")
print(scalar_multiplied)

Original X:
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
Shape: torch.Size([2, 3, 4])

2 + X:
tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])

2 * X:
tensor([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]],

        [[24, 26, 28, 30],
         [32, 34, 36, 38],
         [40, 42, 44, 46]]])


In [6]:
# *는 원소별 곱이고 @는 행렬 곱이다.
# 핵심: A * B는 원소별 곱이고 A @ C는 안쪽 차원을 축약하는 행렬 곱이라 결과 shape 규칙이 다르다.
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = torch.ones(2, 3)
C = torch.ones(3, 2)

elementwise_result = A * B
matrix_result = A @ C

print("A * B:")
print(elementwise_result)
print("Shape:", elementwise_result.shape)

print("\nA @ C:")
print(matrix_result)
print("Shape:", matrix_result.shape)

A * B:
tensor([[0., 1., 2.],
        [3., 4., 5.]])
Shape: torch.Size([2, 3])

A @ C:
tensor([[ 3.,  3.],
        [12., 12.]])
Shape: torch.Size([2, 2])


In [ ]:
# Hadamard product의 gradient도 원소별로 계산된다.
# 핵심: loss = Σ(A ⊙ B)이면 각 Aᵢⱼ에 대한 gradient는 곱해진 상대 원소 Bᵢⱼ다.
A = torch.tensor(
    [[1.0, 2.0], [3.0, 4.0]],
    requires_grad=True,
)
B = torch.tensor([
    [1.0, 9.0],
    [7.0, 4.0],
])

loss = (A * B).sum()
loss.backward()

print("Loss:", loss)
print("Gradient of A:")
print(A.grad)

# loss = Σ(AᵢⱼBᵢⱼ)이므로 ∂loss/∂Aᵢⱼ = Bᵢⱼ다.
assert torch.equal(A.grad, B)

Loss: tensor(61., grad_fn=<SumBackward0>)
Gradient of A:
tensor([[6., 9.],
        [7., 4.]])
