In [1]:
import torch

A = torch.arange(6, dtype=torch.float32).reshape(2, 3)

print("Matrix A:")
print(A)
print("Shape:", A.shape)

Matrix A:
tensor([[0., 1., 2.],
        [3., 4., 5.]])
Shape: torch.Size([2, 3])


In [4]:
total = A.sum()

print("Sum of all elements:", total)
print("Shape:", total.shape)

assert total.item() == 15.0
assert total.shape == ()

Sum of all elements: tensor(15.)
Shape: torch.Size([])


In [ ]:
# dim=0은 행이 나열된 축을 제거하므로 각 열의 합이 남는다.
column_sums = A.sum(dim=0)

# dim=1은 열이 나열된 축을 제거하므로 각 행의 합이 남는다.
row_sums = A.sum(dim=1)

print("Column sums:")
print(column_sums)
print("Shape:", column_sums.shape)

print("\nRow sums:")
print(row_sums)
print("Shape:", row_sums.shape)

Column sums:
tensor([3., 5., 7.])
Shape: torch.Size([3])

Row sums:
tensor([ 3., 12.])
Shape: torch.Size([2])


In [5]:
# 여러 축을 동시에 지정하면 지정된 축이 모두 제거된다.
sum_over_both_axes = A.sum(dim=(0, 1))
sum_over_all_axes = A.sum()

print("Sum over dimensions 0 and 1:", sum_over_both_axes)
print("Sum over every dimension:", sum_over_all_axes)

Sum over dimensions 0 and 1: tensor(15.)
Sum over every dimension: tensor(15.)


In [6]:
mean_value = A.mean()
manual_mean = A.sum() / A.numel()

# dim=0 평균은 각 열의 평균이다.
column_means = A.mean(dim=0)

print("Mean:", mean_value)
print("Manual mean:", manual_mean)

print("\nColumn means:")
print(column_means)
print("Shape:", column_means.shape)

Mean: tensor(2.5000)
Manual mean: tensor(2.5000)

Column means:
tensor([1.5000, 2.5000, 3.5000])
Shape: torch.Size([3])


In [7]:
X = torch.tensor(
    [[1.0, 2.0], [3.0, 4.0]],
    requires_grad=True,
)

loss = X.sum()
loss.backward()

print("Loss:", loss)
print("Gradient:")
print(X.grad)

Loss: tensor(10., grad_fn=<SumBackward0>)
Gradient:
tensor([[1., 1.],
        [1., 1.]])


In [ ]:
# Transformer 출력의 shape는 일반적으로 (B, T, D)다.
B, T, D = 2, 3, 4
hidden_states = torch.arange(
    B * T * D,
    dtype=torch.float32,
).reshape(B, T, D)

# token 축 T를 평균 내면 sequence마다 하나의 벡터가 남는다.
sequence_vectors = hidden_states.mean(dim=1)

print("Hidden states shape:", hidden_states.shape)
print("Sequence vectors shape:", sequence_vectors.shape)

Hidden states shape: torch.Size([2, 3, 4])
Sequence vectors shape: torch.Size([2, 4])


: 