In [1]:
import torch

A = torch.arange(
    6,
    dtype=torch.float32,
).reshape(2, 3)

print(A)
print("Shape:", A.shape)

tensor([[0., 1., 2.],
        [3., 4., 5.]])
Shape: torch.Size([2, 3])


In [6]:
# keepdim=False 이면 축약한 축이 사라진다.
row_sums = A.sum(dim=1)

row_sums_keepdim = A.sum(
    dim=1,
    keepdim=True,
)

print("Without keepdim:")
print(row_sums)
print("Shape:", row_sums.shape)

print("\nWith keepdim:")
print(row_sums_keepdim)
print("Shape:", row_sums_keepdim.shape)

assert row_sums.shape == (2,)
assert row_sums_keepdim.shape == (2, 1)

Without keepdim:
tensor([ 3., 12.])
Shape: torch.Size([2])

With keepdim:
tensor([[ 3.],
        [12.]])
Shape: torch.Size([2, 1])


In [8]:
# [2, 3] / [2, 1] broadcasting으로 각 행을 자신의 합으로 나눈다.
normalized_A = A / row_sums_keepdim

print(normalized_A)

print("\nRow sums:")
print(normalized_A.sum(dim=1))

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

Row sums:
tensor([1., 1.])


In [9]:
# cumsum은 지정한 축을 따라 값을 누적하지만 shape를 축약하지 않는다.
cumulative_sum = A.cumsum(dim=0)

print("Original A:")
print(A)

print("\nCumulative sum along dim=0:")
print(cumulative_sum)
print("Shape:", cumulative_sum.shape)

Original A:
tensor([[0., 1., 2.],
        [3., 4., 5.]])

Cumulative sum along dim=0:
tensor([[0., 1., 2.],
        [3., 5., 7.]])
Shape: torch.Size([2, 3])


In [ ]:
scores = torch.tensor([
    [1.0, 2.0, 3.0],
    [2.0, 2.0, 4.0],
])

denominator = scores.sum(
    dim=-1,
    keepdim=True,
)

weights = scores / denominator

print("Denominator shape:", denominator.shape)
print("Weights:")
print(weights)

print("\nWeight sums:")
print(weights.sum(dim=-1))

Denominator shape: torch.Size([2, 1])
Weights:
tensor([[0.1667, 0.3333, 0.5000],
        [0.2500, 0.2500, 0.5000]])

Weight sums:
tensor([1., 1.])


: 