In [1]:
import torch

A = torch.arange(
    6,
    dtype=torch.float32,
).reshape(2, 3)

x = torch.arange(
    3,
    dtype=torch.float32,
)

print("A:")
print(A)
print("Shape:", A.shape)

print("\nx:")
print(x)
print("Shape:", x.shape)

A:
tensor([[0., 1., 2.],
        [3., 4., 5.]])
Shape: torch.Size([2, 3])

x:
tensor([0., 1., 2.])
Shape: torch.Size([3])


In [3]:
first_element = torch.dot(A[0], x)
second_element = torch.dot(A[1], x)

manual_result = torch.stack([
    first_element,
    second_element,
])

print("First row dot x:", first_element)
print("Second row dot x:", second_element)
print("Manual result:", manual_result)

First row dot x: tensor(5.)
Second row dot x: tensor(14.)
Manual result: tensor([ 5., 14.])


In [ ]:
# torch.mv와 @는 동일한 행렬-벡터 곱을 계산한다.
mv_result = torch.mv(A, x)
operator_result = A @ x

print("torch.mv result:", mv_result)
print("@ result:", operator_result)
print("mv_result shape:", operator_result.shape)
print("operator_result shape:", mv_result.shape)

torch.mv result: tensor([ 5., 14.])
@ result: tensor([ 5., 14.])
Result shape: torch.Size([2])
Result shape: torch.Size([2])


In [ ]:
# 신경망 층은 입력 벡터를 새로운 출력 벡터로 변환한다.
weight = torch.tensor([
    [0.5, 1.0, -0.5],
    [1.0, 0.0,  2.0],
])
input_vector = torch.tensor([2.0, 3.0, 4.0])
bias = torch.tensor([0.1, -0.2])

# y = Wx + b
output_vector = weight @ input_vector + bias 

print("Weight shape:", weight.shape)
print("Input shape:", input_vector.shape)
print("Output:", output_vector)
print("Output shape:", output_vector.shape)


Weight shape: torch.Size([2, 3])
Input shape: torch.Size([3])
Output: tensor([2.1000, 9.8000])
Output shape: torch.Size([2])


In [9]:
# 행렬–벡터 곱을 거쳐 스칼라 loss까지 gradient가 흐르는 경로를 확인한다.

A = torch.tensor(
    [[1.0, 2.0], [3.0, 4.0]],
    requires_grad=True,
)
x = torch.tensor(
    [5.0, 6.0],
    requires_grad=True,
)

y = A @ x
loss = y.sum()
loss.backward()

print("y:", y)
print("Gradient of A:")
print(A.grad)

print("\nGradient of x:")
print(x.grad)

y: tensor([17., 39.], grad_fn=<MvBackward0>)
Gradient of A:
tensor([[5., 6.],
        [5., 6.]])

Gradient of x:
tensor([4., 6.])
