In [ ]:
import torch

A = torch.arange(
    6,
    dtype=torch.float32,
).reshape(2, 3)

B = torch.ones(3, 4)

print("A shape:", A.shape)
print("B shape:", B.shape)

A shape: torch.Size([2, 3])
B shape: torch.Size([3, 4])


In [2]:
# torch.mm과 @는 두 2차원 행렬에서 같은 결과를 만든다.
mm_result = torch.mm(A, B)
operator_result = A @ B

print("A @ B:")
print(operator_result)
print("Shape:", operator_result.shape)

assert torch.equal(mm_result, operator_result)
assert operator_result.shape == (2, 4)

A @ B:
tensor([[ 3.,  3.,  3.,  3.],
        [12., 12., 12., 12.]])
Shape: torch.Size([2, 4])


In [ ]:
# X: (batch_size, input_features)
X = torch.tensor([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
])

# W: (input_features, output_features)
W = torch.tensor([
    [1.0, 0.0],
    [0.0, 1.0],
    [1.0, 1.0],
])

# Y: (batch_size, output_features)
Y = X @ W

print("X shape:", X.shape)
print("W shape:", W.shape)
print("Y:")
print(Y)
print("Y shape:", Y.shape)

X shape: torch.Size([2, 3])
W shape: torch.Size([3, 2])
Y:
tensor([[ 4.,  5.],
        [10., 11.]])
Y shape: torch.Size([2, 2])


In [4]:
Q = torch.tensor([
    [1.0, 0.0, 1.0],
    [0.0, 1.0, 1.0],
])

K = torch.tensor([
    [1.0, 0.0, 0.0],
    [0.0, 1.0, 0.0],
    [1.0, 1.0, 1.0],
    [1.0, 0.0, 1.0],
])

attention_scores = Q @ K.T

print("Q shape:", Q.shape)
print("K shape:", K.shape)
print("K.T shape:", K.T.shape)

print("\nAttention scores:")
print(attention_scores)
print("Shape:", attention_scores.shape)

Q shape: torch.Size([2, 3])
K shape: torch.Size([4, 3])
K.T shape: torch.Size([3, 4])

Attention scores:
tensor([[1., 0., 2., 2.],
        [0., 1., 2., 1.]])
Shape: torch.Size([2, 4])


In [5]:
# C = A @ B의 역전파 shape와 계산 관계를 확인한다.
A = torch.tensor(
    [[1.0, 2.0], [3.0, 4.0]],
    requires_grad=True,
)

B = torch.tensor(
    [[5.0, 6.0], [7.0, 8.0]],
    requires_grad=True,
)

C = A @ B
loss = C.sum()
loss.backward()

print("C:")
print(C)

print("\nA gradient:")
print(A.grad)

print("\nB gradient:")
print(B.grad)

output_gradient = torch.ones_like(C)

expected_A_grad = output_gradient @ B.T
expected_B_grad = A.T @ output_gradient


C:
tensor([[19., 22.],
        [43., 50.]], grad_fn=<MmBackward0>)

A gradient:
tensor([[11., 15.],
        [11., 15.]])

B gradient:
tensor([[4., 4.],
        [6., 6.]])
