In [1]:
import torch

In [2]:
X = torch.tensor([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
])

column_sums = X.sum(
    dim=0,
    keepdim=True,
)

row_sums = X.sum(
    dim=1,
    keepdim=True,
)

print("X:")
print(X)
print("X shape:", X.shape)

print("\nColumn sums:")
print(column_sums)
print("Column sums shape:", column_sums.shape)

print("\nRow sums:")
print(row_sums)
print("Row sums shape:", row_sums.shape)

X:
tensor([[1., 2., 3.],
        [4., 5., 6.]])
X shape: torch.Size([2, 3])

Column sums:
tensor([[5., 7., 9.]])
Column sums shape: torch.Size([1, 3])

Row sums:
tensor([[ 6.],
        [15.]])
Row sums shape: torch.Size([2, 1])


In [3]:
def softmax_from_scratch(logits):
   """수치적으로 안정적인 Softmax 직접 구현."""
   
   # 행별 최대값을 빼서 exp overflow 방지
   shifted_logits = (
           logits # [batch_size, num_classes]
           - logits.max(
                dim=-1,
                keepdim=True,
           ).values # [batch_size, 1]
   )
   
   # [batch_size, num_classes]
   exponentials = shifted_logits.exp()
   
   # 각 데이터의 클래스 점수 합: [batch_size, 1]
   partition = exponentials.sum(
           dim=-1,
           keepdim=True,
   )
   
   # (batch_size, num_classes) / (batch_size, 1)
   # broadcasting으로 행별 정규화를 수행
   return exponentials / partition

In [4]:
logits = torch.rand(2, 5)

manual_probabilities = softmax_from_scratch(
    logits
)

pytorch_probabilities = torch.softmax(
    logits,
    dim=-1,
)

print("Logits:")
print(logits)

print("\nPyTorch Softmax:")
print(pytorch_probabilities)

print("\nManual Softmax:")
print(manual_probabilities)

print("\nRow sums:")
print(manual_probabilities.sum(dim=-1))

Logits:
tensor([[0.4866, 0.8853, 0.2812, 0.6888, 0.3600],
        [0.7288, 0.2953, 0.5693, 0.5483, 0.6491]])

PyTorch Softmax:
tensor([[0.1849, 0.2754, 0.1505, 0.2263, 0.1629],
        [0.2348, 0.1522, 0.2002, 0.1960, 0.2168]])

Manual Softmax:
tensor([[0.1849, 0.2754, 0.1505, 0.2263, 0.1629],
        [0.2348, 0.1522, 0.2002, 0.1960, 0.2168]])

Row sums:
tensor([1.0000, 1.0000])


In [ ]:
# 매우 큰 logit에서도 안정적으로 계산되는지 확인한다.
large_logits = torch.tensor([
    [1000.0, 999.0, 998.0],
])

stable_result = softmax_from_scratch(
    large_logits
)

pytorch_result = torch.softmax(
    large_logits,
    dim=-1,
)

print("Stable manual Softmax:")
print(stable_result)

print("\nPyTorch Softmax:")
print(pytorch_result)

assert torch.allclose(
    stable_result,
    pytorch_result,
)

Stable manual Softmax:
tensor([[0.6652, 0.2447, 0.0900]])

PyTorch Softmax:
tensor([[0.6652, 0.2447, 0.0900]])


: 