In [29]:
import torch
from torch import nn
from d2l import torch as d2l

In [30]:
# 2D Pooling Implementation

def pool2d(
    X: torch.Tensor, # [H, W]
    pool_size: tuple[int, int],
    mode: str = "max",
) -> torch.Tensor:
    
    if mode not in {"max", "avg"}:
        raise ValueError(
            "mode must be max or avg."
        )

    pool_height, pool_width = pool_size

    output_height = X.shape[0] - pool_height + 1
    output_width = X.shape[1] - pool_width + 1
    
    Y = torch.zeros(
        (output_height, output_width),
        dtype=X.dtype,
        device=X.device,
    )
    
    for i in range(output_height):
        for j in range(output_width):
            window = X[
                i : i + pool_height,
                j : j + pool_width,
            ] # window.shape[pool_height, pool_width]
            
            if mode == "max":
                Y[i, j] = window.max()
            else:
                Y[i, j] = window.mean()
                
    return Y

In [31]:
# Max-pooling & Average Pooling

X = torch.tensor([
    [0.0, 1.0, 2.0],
    [3.0, 4.0, 5.0],
    [6.0, 7.0, 8.0],
])

max_pooled = pool2d(
    X, 
    pool_size=(2, 2),
    mode="max",
)

average_pooled = pool2d(
    X,
    pool_size=(2, 2),
    mode="avg",
)

print("X:")
print(X)

print("\nMax-pooling:")
print(max_pooled)

print("\nAverage pooling:")
print(average_pooled)

X:
tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

Max-pooling:
tensor([[4., 5.],
        [7., 8.]])

Average pooling:
tensor([[2., 3.],
        [5., 6.]])
