In [1]:
import torch
from torch import nn
from d2l import torch as d2l

In [2]:
# Default Stride

X_4d = torch.arange(
    16,
    dtype=torch.float32,
).reshape((1, 1, 4, 4))

# stride 생략 시, 다음처럼 설정
# stride = kernel_size = 3
default_pool = nn.MaxPool2d(
    kernel_size=3,
)

Y_default = default_pool(X_4d)

print("X:")
print(X_4d)

print("\nDefault pooling output:")
print(Y_default)

print("Output shape:", Y_default.shape)

X:
tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

Default pooling output:
tensor([[[[10.]]]])
Output shape: torch.Size([1, 1, 1, 1])


In [3]:
# Custom Padding과 Stride

custom_pool = nn.MaxPool2d(
    kernel_size=3,
    padding=1,
    stride=2,
)

rectangular_pool = nn.MaxPool2d(
    kernel_size=(2, 3),
    padding=(0, 1),
    stride=(2, 3),
)

Y_custom = custom_pool(X_4d)
Y_rectangular = rectangular_pool(X_4d)

print("Custom pooling:")
print(Y_custom)

print("\nRectangular pooling:")
print(Y_rectangular)

Custom pooling:
tensor([[[[ 5.,  7.],
          [13., 15.]]]])

Rectangular pooling:
tensor([[[[ 5.,  7.],
          [13., 15.]]]])
